#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerate paraforge/catalog.py from an installed copy of Paralives.

The Build Mode tag list is not published anywhere, and it is what decides
where an item lands in the catalogue and what base price it gets. Rather than
guess at it, read it out of the game's own mod folder:

    python tools/extract_catalog.py "C:/Games/Paralives/Main.mod"

Run this again after a game update. Nothing else in the add-on needs touching.
"""

import os
import re
import sys

HEADER = '''# SPDX-License-Identifier: GPL-3.0-or-later
"""Build Mode catalogue tags, read out of the game itself.

Generated by tools/extract_catalog.py from Main.mod/Settings, game build
{version}. Do not edit by hand: run the tool again after a game update.

Each entry is (guid, name, parent_guid_or_empty, depth). The GUID is what an
item's Tag list actually stores, so it is the part that has to be exact.
"""

#: Game build these tags were read from.
SOURCE_BUILD = "{version}"

#: (guid, name, parent, depth), in catalogue order.
TAGS = (
{rows}
)

BY_GUID = {{guid: (name, parent, depth) for guid, name, parent, depth in TAGS}}
BY_NAME = {{name: guid for guid, name, _parent, _depth in TAGS}}


def label(guid):
    entry = BY_GUID.get(guid)
    return entry[0] if entry else guid


def indented_label(guid):
    """Name prefixed by its depth, so a flat dropdown still reads as a tree."""
    entry = BY_GUID.get(guid)
    if entry is None:
        return guid
    name, _parent, depth = entry
    return ("    " * depth) + name


def children(guid):
    return [g for g, _n, parent, _d in TAGS if parent == guid]


def path(guid):
    """Full ancestry as a single readable string."""
    parts = []
    seen = set()
    current = guid
    while current and current in BY_GUID and current not in seen:
        seen.add(current)
        name, parent, _depth = BY_GUID[current]
        parts.append(name)
        current = parent
    return " > ".join(reversed(parts))
'''


def parse(lines):
    root = {}
    stack = [(-1, root)]
    for line in lines:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        depth = len(line) - len(line.lstrip(" "))
        body = line.strip()
        while len(stack) > 1 and stack[-1][0] >= depth:
            stack.pop()
        parent = stack[-1][1]
        if body.startswith("="):
            key, sep, value = body[1:].partition(":")
            if sep:
                parent[key] = value
            else:
                child = {}
                parent[key] = child
                stack.append((depth, child))
        else:
            child = {}
            parent[body] = child
            stack.append((depth, child))
    return root


def entries(node):
    listed = [(int(k[1:]), v) for k, v in node.items() if re.fullmatch(r"i\d+", k)]
    return [v for _k, v in sorted(listed)]


def linked(node, key):
    child = node.get(key)
    if not isinstance(child, dict):
        return []
    return [e.get("Value") for e in entries(child) if e.get("Value")]


def game_version(mod_root):
    for directory, _dirs, names in os.walk(os.path.join(mod_root, "Settings")):
        for name in names:
            if not name.endswith(".meta"):
                continue
            with open(os.path.join(directory, name), encoding="utf-8",
                      errors="replace") as handle:
                for line in handle:
                    if line.startswith("UpdatedToGameVersion:"):
                        return line.split(":", 1)[1].strip()
    return "unknown"


def main(argv):
    if len(argv) < 2:
        raise SystemExit(__doc__)
    mod_root = argv[1]
    settings = os.path.join(mod_root, "Settings", "BuildModeCatalogTags.setting")
    if not os.path.isfile(settings):
        raise SystemExit("Not a Main.mod folder: " + settings + " is missing")

    with open(settings, encoding="utf-8", errors="replace") as handle:
        tree = parse(handle.read().splitlines())

    tags = entries(tree["Tags"])
    by_guid = {t["GUID"]: t for t in tags if "GUID" in t}

    parents = {}
    order = {}
    for tag in tags:
        for index, child in enumerate(linked(tag, "ChildTags")):
            parents[child] = tag["GUID"]
            order[child] = index

    def depth_of(guid, seen=None):
        seen = seen or set()
        parent = parents.get(guid)
        if not parent or parent in seen:
            return 0
        seen.add(guid)
        return 1 + depth_of(parent, seen)

    # A tag can hang under more than one parent, Stairs sits under both Build
    # and StairsAndLadders. Each GUID may only appear once: it becomes an enum
    # identifier, and Blender will not take a duplicate.
    rows = []
    placed = set()

    def walk(guid, depth):
        tag = by_guid.get(guid)
        if tag is None or guid in placed:
            return
        placed.add(guid)
        rows.append((guid, tag.get("DisplayName", guid), parents.get(guid, ""),
                     depth))
        kids = sorted(linked(tag, "ChildTags"), key=lambda g: order.get(g, 0))
        for child in kids:
            walk(child, depth + 1)

    for tag in tags:
        guid = tag.get("GUID")
        if guid and guid not in parents:
            walk(guid, 0)

    # Anything the tree missed, so nothing is silently dropped.
    for tag in tags:
        guid = tag.get("GUID")
        if guid and guid not in placed:
            placed.add(guid)
            rows.append((guid, tag.get("DisplayName", guid),
                         parents.get(guid, ""), depth_of(guid)))

    body = "\n".join(
        '    ("{0}", "{1}", "{2}", {3}),'.format(*row) for row in rows
    )
    text = HEADER.format(version=game_version(mod_root), rows=body)

    target = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "paraforge", "catalog.py",
    )
    with open(target, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print("{0} tags -> {1}".format(len(rows), target))


if __name__ == "__main__":
    main(sys.argv)
